export const menuItems = [
  { name: "Empanada de Viento", sizes: ["Pequeña", "Mediana", "Gigante"], "price": 2.5 },
  { name: "Empanada de Morocho", sizes: ["Pequeña", "Grande"], "price": 2.5 },
  { name: "Pristiños", sizes: ["Pequeño", "Mediano", "Grande"], "price": 2.5 },
  { name: "Empanada de Verde", sizes: ["Pequeña", "Grande", "Bonitísima"], "price": 2.5 },
  { name: "Humitas", "price": 2.5 },
  { name: "Bolones" , "price": 2.5},
  { name: "Salchipapas" , "price": 2.5},
  { name: "Mote con Chicharrón" , "price": 2.5},
  { name: "Fritada" , "price": 2.5},
  { name: "Llapingacho" , "price": 2.5},
  { name: "Locro de Papa" , "price": 2.5},
  { name: "Seco de Chivo" , "price": 2.5},
  { name: "Ponche" , "price": 2.5},
  { name: "Colada Morada" , "price": 2.5},
  { name: "Chocolate de Ambato" , "price": 2.5},
  { name: "Canelazo" , "price": 2.5},
  { name: "Vino Hervido" , "price": 2.5},
  { name: "Morocho", "price": 2.5 },
  { name: "Cerveza" , "price": 2.5},
  { name: "Micheladas" , "price": 2.5},
  { name: "Batidos" , "price": 2.5},
  { name: "Limonadas" , "price": 2.5},
  { name: "Jugos", "price": 2.5 },
  { name: "Colas", "price": 2.5 },
  { name: "Aguas", "price": 2.5 },
  { name: "Colada de Machica", "price": 2.5 },
];
