export const menuItems = [
  { name: "Empanada de Viento", sizes: ["Pequeña", "Mediana", "Gigante"] },
  { name: "Empanada de Morocho", sizes: ["Pequeña", "Grande"] },
  { name: "Pristiños", sizes: ["Pequeño", "Mediano", "Grande"] },
  { name: "Empanada de Verde", sizes: ["Pequeña", "Grande", "Bonitísima"] },
  { name: "Humitas" },
  { name: "Bolones" },
  { name: "Salchipapas" },
  { name: "Mote con Chicharrón" },
  { name: "Fritada" },
  { name: "Llapingacho" },
  { name: "Locro de Papa" },
  { name: "Seco de Chivo" },
  { name: "Ponche" },
  { name: "Colada Morada" },
  { name: "Chocolate de Ambato" },
  { name: "Canelazo" },
  { name: "Vino Hervido" },
  { name: "Morocho" },
  { name: "Cerveza" },
  { name: "Micheladas" },
  { name: "Batidos" },
  { name: "Limonadas" },
  { name: "Jugos" },
  { name: "Colas" },
  { name: "Aguas" },
  { name: "Colada de Machica" },
];
